ADD_SCENE(disney_beacons_app, menu, Menu)
ADD_SCENE(disney_beacons_app, input_mac_addr, InputMacAddress)
ADD_SCENE(disney_beacons_app, input_beacon_data, InputBeaconData)
ADD_SCENE(disney_beacons_app, run_beacon, RunBeacon)
ADD_SCENE(disney_beacons_app, input_ears_data, InputEarsData)
